### ISSUE TITLE
[bug] Under node. js v18, some operations of laf cli may report errors

### ISSUE THREAD

**Issue by NMTuan** [labring/laf#1445]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

https://laf.run

### What happened

some operations of laf cli may report errors

eg: laf func pull func_name

![image](https://github.com/labring/laf/assets/2149763/57e118fd-f8a2-436c-8e76-b85fd98ccbbf)

### How to reproduce

laf.yaml

```yaml
name: test_api
appid: xyvklh
createdAt: 2023-04-11T13:18:07.032Z
invokeUrl: https://xyvklh.laf.run

```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!
