### ISSUE TITLE
laf登录态的保持体验不好，总是开发过程中需要重新登录，而且还会跳回面板首页，函数页面都要重开。

### ISSUE THREAD

**Issue by akiiity** [labring/laf#302]

**Comment by maslow** [comment]
token 应该被一些失败请求意外清理了，我再检查一下

**Comment by akiiity** [comment]
@maslow token有效期只有1天对吗，会不会有点短呀？

**Comment by maslow** [comment]
lafyun 默认是7天有效期，你是私有部署版的是吗？

**Comment by akiiity** [comment]
对，私有化部署的。

**Comment by maslow** [comment]
OK，默认部署的配置确实是 24小时， 可以通过给 system-server 配置一个环境变量 `TOKEN_EXPIRED_TIME` 来修改，单位是 hour，默认值 24.

```yaml
 system-server:
    image: lafyun/system-server:latest
    user: root
    working_dir: /app
    environment:
        TOKEN_EXPIRED_TIME: 720
        #....
```

然后重启 system-server 服务：`docker-compose restart system-server` or `docker-compose up -d`
