### ISSUE TITLE
本地部署该如何提供https证书？

### ISSUE THREAD

**Issue by x956606865** [labring/laf#88]
请问本地部署该如何提供https证书？在文档里似乎没有看到类似的环境变量设置

**Comment by maslow** [comment]
Hi @x956606865 , 请问你是基于 docker-compose 模式部署，还是基于 k8s 部署的呢？

如果是 k8s，比较简单，直接修改相应的 ingress 添加 tls 字段即可：
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-sys
  namespace: lafyun
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - www.lafyun.com
    secretName: lafyun-tls-secret
  rules:
  - host: www.lafyun.com
     # ....
```
